spring:
  datasource:
    #durid连接池配置
    druid:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:@localhost:1521:ORCL
      username: mtest
      password: mtest
  application:
    name: demo-boot
server:
  port: 9310